### ISSUE TITLE
自增id序列函数的bug

### ISSUE THREAD

**Issue by mayuanxiaonong** [MyCATApache/Mycat-doc#22]
入门指南\sequnce-sql.txt第13行   SET retval="-999999999,null";    步进值不能是null    如果MYCAT_SEQUENCE中没有对应的记录 返回null   程序解析为int类型是会抛出NumberFormatException异常

**Comment by runfriends** [comment]
只有配置不对才会出这个异常



runfriends@126.com
 
发件人： 码园小农
发送时间： 2015-05-22 14:42
收件人： MyCATApache/Mycat-doc
主题： [Mycat-doc] 自增id序列函数的bug (#22)
入门指南\sequnce-sql.txt第13行 SET retval="-999999999,null"; 步进值不能是null 如果MYCAT_SEQUENCE中没有对应的记录 返回null 程序解析为int类型是会抛出NumberFormatException异常

**Comment by mayuanxiaonong** [comment]
了解了，通过带null 的一个默认值  给用户抛出一个异常信息。  如果数据表不存在而又返回一个正常的默认值，比如-99999999,1000，那么下次再获取序列还是这个值，会主键冲突。
