### ISSUE TITLE
1.4,1.5链接ERROR 1003 (HY000): Unsupported statement

### ISSUE THREAD

**Issue by Icecream0211** [MyCATApache/Mycat-doc#46]
系统：ubuntu16.04，mysql 5.7
按照mycat-doc下的入门两节点配置，1.4-release和1.5-release配置完成，可以正常启动，但是总是出现
ERROR 1003 (HY000): Unsupported statement

jdk环境
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by tianzhenjiu** [comment]
你问题最后是怎么解决的？
