### ISSUE TITLE
druid解析问题；mycat版本1.3.0.1

### ISSUE THREAD

**Issue by Timxuhj** [MyCATApache/Mycat-doc#8]
使用druid解析器，发现explain节点数据有问题：
127.0.0.1/root:[TESTDB> EXPLAIN SELECT * FROM test WHERE id >= 11000 AND id <= 1111100;
+-----------+--------------------------------------------------------+
| DATA_NODE | SQL                                                    |
+-----------+--------------------------------------------------------+
| dn1       | SELECT * FROM test WHERE id >= 11000 AND id <= 1111100 |
+-----------+--------------------------------------------------------+
1 row in set (0.12 sec)
5个节点，只定位到一个节点。
注释掉druid解析器后：
127.0.0.1/root:[TESTDB> EXPLAIN SELECT * FROM test WHERE id >= 11000 AND id <= 1111100;
+-----------+----------------------------------------------------------------------+
| DATA_NODE | SQL                                                                  |
+-----------+----------------------------------------------------------------------+
| dn1       | SELECT * FROM test WHERE (id >= 11000) AND (id <= 1111100) LIMIT 100 |
| dn2       | SELECT * FROM test WHERE (id >= 11000) AND (id <= 1111100) LIMIT 100 |
| dn3       | SELECT * FROM test WHERE (id >= 11000) AND (id <= 1111100) LIMIT 100 |
| dn4       | SELECT * FROM test WHERE (id >= 11000) AND (id <= 1111100) LIMIT 100 |
| dn5       | SELECT * FROM test WHERE (id >= 11000) AND (id <= 1111100) LIMIT 100 |
+-----------+----------------------------------------------------------------------+
5 rows in set (0.00 sec)

mycat版本1.3.0.1，linux-x64

**Comment by wdw1206** [comment]
已修复，请使用1.4dev版本验证
